### PR TITLE
Update to Symbolics v5

### PR DESCRIPTION
**Pull request by david-pl**
Fixed an issue that caused `subsitute` to fail on the SymbolicUtils version.

@j-moser tests still fail because of indexing: the second type-parameter of `SymbolicUtils.Sym` was removed, so types such as `SymbolicUtils.Sym{Parameter,IndexedVariable}` are no longer valid. This means that dispatches on such types have to be changed (maybe using `if` clauses?). Could you take a look at this?

It might be that other tests fail as well, but I wasn't able to test everything due to dependence on indexing.

### CODE REVIEW

**Comment by j-moser** [comment]
@david-pl I created a new PR for the Symbolics.jl v5 update into the branch `symbolics-v5-update`. All tests should be running for this version and Symbolics v5. However, I needed to change quite a bit, especially the types of Averages and Parameters. Some more testing might be needed, maybe you can have a look at it.

**Comment by david-pl** [comment]
@j-moser thanks for all the work! I had to do some small adaptions to make tests pass and the docs build. Also did some minor clean up. Could you give it another quick review? Otherwise it's good to merge IMO.

**Comment by j-moser** [comment]
Hey @david-pl, I had a look at the commits of yours and also ran some other programs I had lying around. Everything seems to work as intended.

**Comment by david-pl** [comment]
@j-moser perfect, thanks a lot!

**Pull request merged**
